<?php return array (
  'name' => 'UD Harapan Baru',
  'icon' => 'img/img-company.svg',
  'log' => 'errorlog',
  'env' => 'local',
  'debug' => true,
  'url' => 'http://salesfusion.tunggaljayasurabaya.web.id',
  'asset_url' => NULL,
  'timezone' => 'UTC',
  'locale' => 'en',
  'fallback_locale' => 'en',
  'faker_locale' => 'en_US',
  'key' => 'base64:QEsiR//Pyvf+4e+Evg94tYlNWqhVbm0Z43FDAWOVxfs=',
  'cipher' => 'AES-256-CBC',
  'providers' => 
  array (
    0 => 'Illuminate\\Auth\\AuthServiceProvider',
    1 => 'Illuminate\\Broadcasting\\BroadcastServiceProvider',
    2 => 'Illuminate\\Bus\\BusServiceProvider',
    3 => 'Illuminate\\Cache\\CacheServiceProvider',
    4 => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider',
    5 => 'Illuminate\\Cookie\\CookieServiceProvider',
    6 => 'Illuminate\\Database\\DatabaseServiceProvider',
    7 => 'Illuminate\\Encryption\\EncryptionServiceProvider',
    8 => 'Illuminate\\Filesystem\\FilesystemServiceProvider',
    9 => 'Illuminate\\Foundation\\Providers\\FoundationServiceProvider',
    10 => 'Illuminate\\Hashing\\HashServiceProvider',
    11 => 'Illuminate\\Mail\\MailServiceProvider',
    12 => 'Illuminate\\Notifications\\NotificationServiceProvider',
    13 => 'Illuminate\\Pagination\\PaginationServiceProvider',
    14 => 'Illuminate\\Pipeline\\PipelineServiceProvider',
    15 => 'Illuminate\\Queue\\QueueServiceProvider',
    16 => 'Illuminate\\Redis\\RedisServiceProvider',
    17 => 'Illuminate\\Auth\\Passwords\\PasswordResetServiceProvider',
    18 => 'Illuminate\\Session\\SessionServiceProvider',
    19 => 'Illuminate\\Translation\\TranslationServiceProvider',
    20 => 'Illuminate\\Validation\\ValidationServiceProvider',
    21 => 'Illuminate\\View\\ViewServiceProvider',
    22 => 'App\\Providers\\AppServiceProvider',
    23 => 'App\\Providers\\AuthServiceProvider',
    24 => 'App\\Providers\\EventServiceProvider',
    25 => 'App\\Providers\\RouteServiceProvider',
    26 => 'Spatie\\Backup\\BackupServiceProvider',
  ),
  'aliases' => 
  array (
    'App' => 'Illuminate\\Support\\Facades\\App',
    'Arr' => 'Illuminate\\Support\\Arr',
    'Artisan' => 'Illuminate\\Support\\Facades\\Artisan',
    'Auth' => 'Illuminate\\Support\\Facades\\Auth',
    'Blade' => 'Illuminate\\Support\\Facades\\Blade',
    'Broadcast' => 'Illuminate\\Support\\Facades\\Broadcast',
    'Bus' => 'Illuminate\\Support\\Facades\\Bus',
    'Cache' => 'Illuminate\\Support\\Facades\\Cache',
    'Config' => 'Illuminate\\Support\\Facades\\Config',
    'Cookie' => 'Illuminate\\Support\\Facades\\Cookie',
    'Crypt' => 'Illuminate\\Support\\Facades\\Crypt',
    'Date' => 'Illuminate\\Support\\Facades\\Date',
    'DB' => 'Illuminate\\Support\\Facades\\DB',
    'Eloquent' => 'Illuminate\\Database\\Eloquent\\Model',
    'Event' => 'Illuminate\\Support\\Facades\\Event',
    'File' => 'Illuminate\\Support\\Facades\\File',
    'Gate' => 'Illuminate\\Support\\Facades\\Gate',
    'Hash' => 'Illuminate\\Support\\Facades\\Hash',
    'Http' => 'Illuminate\\Support\\Facades\\Http',
    'Js' => 'Illuminate\\Support\\Js',
    'Lang' => 'Illuminate\\Support\\Facades\\Lang',
    'Log' => 'Illuminate\\Support\\Facades\\Log',
    'Mail' => 'Illuminate\\Support\\Facades\\Mail',
    'Notification' => 'Illuminate\\Support\\Facades\\Notification',
    'Password' => 'Illuminate\\Support\\Facades\\Password',
    'Queue' => 'Illuminate\\Support\\Facades\\Queue',
    'RateLimiter' => 'Illuminate\\Support\\Facades\\RateLimiter',
    'Redirect' => 'Illuminate\\Support\\Facades\\Redirect',
    'Request' => 'Illuminate\\Support\\Facades\\Request',
    'Response' => 'Illuminate\\Support\\Facades\\Response',
    'Route' => 'Illuminate\\Support\\Facades\\Route',
    'Schema' => 'Illuminate\\Support\\Facades\\Schema',
    'Session' => 'Illuminate\\Support\\Facades\\Session',
    'Storage' => 'Illuminate\\Support\\Facades\\Storage',
    'Str' => 'Illuminate\\Support\\Str',
    'URL' => 'Illuminate\\Support\\Facades\\URL',
    'Validator' => 'Illuminate\\Support\\Facades\\Validator',
    'View' => 'Illuminate\\Support\\Facades\\View',
  ),
  'company' => 
  array (
    'name' => 'UD Harapan Baru',
    'about' => 'SalesFusion is a comprehensive application that combines sales management, inventory management, as well as ERP and CRM solutions to help companies efficiently manage their operations.',
    'address' => 'Kampung Seng no 77, Simokerto, Surabaya',
    'telp' => '+6285101440330',
    'email' => 'udharapan.teknik@gmail.com',
    'image_company' => 'img/1698312222-IMG_1461.png',
    'lat' => '-7.2367432',
    'lng' => '112.7486677',
    'saldo' => '0',
  ),
);